name: Schedule Data Refresh

on:
  schedule:
    - cron: '0 4 * * *' # Every day at 4 a.m.
  workflow_dispatch:

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger data refresh
        run: curl -X GET https://codaez-api.onrender.com/api/v1/details/refreshuserdata
